name: Banezaka
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
paginate: 10
paginate_path: "/blog/page:num/"

# Conversion markdown: redcarpet 
highlighter: pygments 
redcarpet: extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
