name: Banezaka
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
paginate: 10
paginate_path: "/blog/page:num/"

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: text
